### ISSUE TITLE
cdoom doesn't work

### ISSUE THREAD

**Issue by acowle3** [dhewm/dhewm3-sdk#1]
I tried out the branch that uses the cdoom mod, and it doesn't work.

At first, I tried the path /user/lib/x86_64-linux-gnu/dhewm3/cdoom.so

Then, I tried /user/lib/x86_64-linux-gnu/dhewm3/cdoom/cdoom.so

Neither works, and when I boot up Dhewm3 and go to the mods menu, it never shows up.

**Comment by DanielGibson** [comment]
Are those paths where the base.so and d3xp.so lie?
Where did you put the cdoom game data?

**Comment by acowle3** [comment]
The first path is also where base.so lie.

I do not have resurrection of evil installed, I'll do that later.

**Comment by DanielGibson** [comment]
ok, what about the game data

**Comment by acowle3** [comment]
Never mind, when you brought up game data, all I had to do was to download the mod itself and extract the PK4s.

**Comment by DanielGibson** [comment]
mate, what do you think why I linked that in the README.txt of cdoom and said to extract it to the install dir :-P

**Comment by DanielGibson** [comment]
BTW, you shouldn't have to extract the PK4s - you just need a cdoom/ dir next to base/ that contains the .pk4 files from cdoom (and maybe the other files from the cdoom .zip as well)

**Comment by acowle3** [comment]
Alright.  Everything works just fine except for one thing:  Why doesn't the custom resolutions work?  You have some really nice widescreen settings in your engine, why doesn't it carry over to CDoom?

**Comment by DanielGibson** [comment]
Because those settings were an ugly hack that only works when the .gui file has the same name as the one used by the main game for that purpose and when the field in that gui for setting the resolutions has the same name as in the original doom3 gui.

There's nothing I can do about this, the way menus (and GUIs in general) work in Doom3 is very inflexible from the engine point of view.
(OTOH it's very flexible from the GUI point of view, you can do a lot of things just with GUIs and scripts without changing anything in the C++ source - but that doesn't exactly help me)

**Comment by acowle3** [comment]
Hmmm...I'm can handle editing text files, at least for now.  that's what I did for vanilla Doom 3.  What text file do I need to edit to solve the problem?

**Comment by DanielGibson** [comment]
Probably cdoom_main.pk4 guis/mainmenu.gui around line 666
I think that `"3;4;5;6;7;8"` are the modes that are shown there (see `r_mode` CVar, and `listModes` command for a list) - the text for the modes will be from `"#str_04222"` which references a translated string, probably from strings/english.lang - look for #str_04222 there, it should define a list of resolutions.
So you'd have to edit the `values` (3;4;5;6;7;8;9;10 etc) in mainmenu.gui line 666 to contain all the modes you want, and that entry in english.lang to have the corresponding list of resolutions (like 640x480;800x600;1024x768 and so on)
