### ISSUE TITLE
updating hardcorps to 1.5.1

### ISSUE THREAD

**Issue by revility** [dhewm/dhewm3-sdk#21]
I'm looking into releasing what is currently done for the Dhewm 3 version of HardQore...

However I'm curious if any of the changes here for 1.5.1 should be updated on the repository I've been using for changed files only:
https://github.com/revility/hardcorps

**Comment by DanielGibson** [comment]
Hi reveility,
sorry I forgot to answer earlier.
I'm not sure which changes you already have and which not, as your repo is not based on this one.
If in doubt, all the changes I did here are useful, except maybe the ones only affecting the README :-P

I think none are strictly necessary (Mods for dhewm3 1.5.0 still work with 1.5.1), but several bugs were fixed, and savegames now store additional information about the system and an internal savegame version, which should help with preserving savegame compatibility in the future, even when changing the savegame format in the mod (e.g. saving additional values for entities)

**Comment by revility** [comment]
The repo I have is based off 1.5.0.  the cmake file and all other files not in the repo are 1.5.1 based
After posting this I looked through the changed files to the ones i have been working on the past few years.  It looks like it is only a handful of files I have in my repo that need to be updated to have all the 1.5.1 updates in it.  The save game stuff did seem to be most obviously needed.  I'll get these going after wrapping up any other sdk fixes needed.
