### ISSUE TITLE
Planning an SDK port for the mod "Perfected Doom 3"

### ISSUE THREAD

**Issue by RPerrodin** [dhewm/dhewm3-sdk#22]
I would like to contribute to the Dhewm3 source port by making my favorite mod playable on it. So I did the direct way of adding the source code to the sdk repository and compile the .so files (I'm on Linux)

However when I run the executable with './dhewm3 +set fs_game perfected' I'm getting an error message:

----- Game Map Shutdown -----
********************
ERROR: Error: file script/doom_events.script, line 13: Unknown event 'isLowered'

I don't know how I can address this so any help would be appreciated.

EDIT: I tried to redo the .so file since I didn't take into account the added .cpp and .h files in both the game and d3xp folders.

However when I try to recompile the .so files I get this error message: 

/home/username/dhewm3/dhewm3-sdk-perfected/game/../idlib/../renderer/qgl.h:45:10: fatal error: SDL_opengl.h: No such file or directory
   45 | #include <SDL_opengl.h>
      |          ^~~~~~~~~~~~~~

I installed and compiled the latest release of SDL2 and is in fact located at /usr/include/SDL2

I don't know what is wrong now.

**Comment by DanielGibson** [comment]
I think the problem is that building the .so failed.

I wonder why that SDL include is in there (the SDK shouldn't use SDL) and why I haven't noticed that before..
I'll look into it this weekend, but you could try if commenting out `#include <SDL_opengl.h>` fixes the build

**Comment by DanielGibson** [comment]
Ok, I think the reason I never noticed this is that in the "pure" SDK and the existing mods `qgl.h` isn't included anywhere, so it's unused.
Are you sure you need it? IMO mods should be independent of the renderering backend and thus shouldn't call OpenGL directly.

**Comment by RPerrodin** [comment]
PD3 also mods lighting and most graphic rendering too. I would love to be able to isolate gameplay from its graphical modifications.

**Comment by DanielGibson** [comment]
Could you share the git repo with your modified dhewm3 sdk code?

**Comment by DanielGibson** [comment]
I briefly looked at the "Perfected Doom 3 version 7 Source Code" and there is not a single call to an opengl function in it.
Are you sure you need qgl.h?

**Comment by RPerrodin** [comment]
Hi,

I'm coming back to this issue I suspended for quite a while. PD3 uses many times the idlib/precompiled.h available on the GPL Doom 3 source code so what I did is simply replace the whole part below header declarations (including the comment in the box) in the SDK source files with the PD3 sources. 

I still can't build something proper so I'm not exactly sure if I need to start over and surgically select the added parts or if I can still work from what I started. If need be, feel free to ask me to make a repository for this.

By the way, VCGames gave me permission on the Blood Discord group to port his mod on Dhewm3 but acknowledge it uses the sikk mod. I'll understand if you don't want to help further for an issue you can't solve then legally release the output.

**Comment by RPerrodin** [comment]
I've made my own fork and I did my first commit. If you could please help debug it with me that would be awesome.
