### ISSUE TITLE
cdoom: "shutting down: Couldn't load default.cfg"

### ISSUE THREAD

**Issue by T-X** [dhewm/dhewm3-sdk#31]
I tried starting the "Classic Doom 3" mod, but I'm getting the following error on the console: "shutting down: Couldn't load default.cfg".

I've used the link [here](https://dhewm3.org/mods.html#classic-doom-3) to download it from ModDB. And unpacked the cdoom folder from the zip file to ~/.local/share/dhewm3/.

I'm on Debian Sid and am using the dhewm3 package Debian provides (1.5.2+dfsg-1). Downloading and unpacking the Doom3 demo to ~/.local/share/dhewm3/demo/ and then starting it worked without any issues.

The full console log output looks as follows:

```
$ dhewm3 +set fs_game cdoom
dhewm3 1.5.2.1305 linux-x86_64 Jun 13 2022 13:37:42 using SDL v2.28.0
SDL video driver: x11
Logging console output to /home/linus/.local/share/dhewm3/dhewm3log.txt
terminal support enabled ( use +set in_tty 0 to disable )
pid: 1941073
30848 MB System Memory
found interface lo - loopback
found interface br0 - 192.168.23.1/255.255.255.0
found interface wlp1s0 - 10.204.36.69/255.255.240.0
doom using MMX & SSE & SSE2 for SIMD processing
enabling Flush-To-Zero mode
enabling Denormals-Are-Zero mode
WARNING: base path '/usr/share/games/doom3' does not exist
----- Initializing File System -----
Loaded pk4 /home/linus/.local/share/dhewm3/cdoom/cdoom_main.pk4 with checksum 0x9ff6284b
Loaded pk4 /home/linus/.local/share/dhewm3/cdoom/cdoom_maps.pk4 with checksum 0xa7bb2433
Loaded pk4 /home/linus/.local/share/dhewm3/cdoom/cdoom_models.pk4 with checksum 0x22e8b18
Loaded pk4 /home/linus/.local/share/dhewm3/cdoom/cdoom_sounds.pk4 with checksum 0xae50243c
Loaded pk4 /home/linus/.local/share/dhewm3/cdoom/cdoom_textures.pk4 with checksum 0x1be0b07f
Current search path:
/home/linus/.config/dhewm3/cdoom
/home/linus/.local/share/dhewm3/cdoom
/home/linus/.local/share/dhewm3/cdoom/cdoom_textures.pk4 (163 files)
/home/linus/.local/share/dhewm3/cdoom/cdoom_sounds.pk4 (113 files)
/home/linus/.local/share/dhewm3/cdoom/cdoom_models.pk4 (449 files)
/home/linus/.local/share/dhewm3/cdoom/cdoom_maps.pk4 (66 files)
/home/linus/.local/share/dhewm3/cdoom/cdoom_main.pk4 (456 files)
/home/linus/.config/dhewm3/base
/home/linus/.local/share/dhewm3/base
Addon pk4s:
shutting down: Couldn't load default.cfg
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
Sys_Error: Couldn't load default.cfg
shutdown terminal support
```

**Comment by T-X** [comment]
@DanielGibson Ah, thanks for the clarification! Then I misread https://dhewm3.org/mods.html#classic-doom-3, I guess. I thought the "Classic Doom3" mod was supposed to be an attempt to provide a 100% free software experience for the 1st episode of Doom 3.

Maybe it would make sense to add a note about requiring the full game version on that page? (Or did I miss it there?)

---

PS/Off-topic: Also many thanks for maintaining this! Trying the demo brought me right back to the unique, scary experience we had back then :-). Back then Doom 3 was also the reason my friends and I all had to get a surround sound system :D.

**Comment by DanielGibson** [comment]
It says
> Classic Doom 3 is a remake of the first episode of the original Doom in Doom3.

It's a remake of the first Episode of Doom from 1993 for Doom3, but a regular mod for Doom3 that requires the full version of the game.

I'll add a note that the mods (except for Fitz Packerton) require the full version of the game

**Comment by DanielGibson** [comment]
I guess this can be closed then?
