### ISSUE TITLE
ruiner runtime errors

### ISSUE THREAD

**Issue by revility** [dhewm/dhewm3-sdk#5]
We've come across 2 c++ runtime errors in Ruiner so far.  Both crashes are rare and hard to replicate and there is nothing in the console when it happens.  Game will crash and the runtime error pops up.

assertion failure
renderworld.cpp line 954
expression bound [0][0].... (i'll write the full details if you need it)

Seems to happen most when cacodemons or something that inherits from them is around.  I can not confirm this the only thing to cause it.

The second is sound related.  This one is rare too.  Seems to happen if you hit escape just immediately after a level loads.

assertion failure
snd_decoder.cpp line 525
expression false

A side note:  I have not tested the mod with the source hook removed version yet and this is from my fork.  Both were in win 64bit versions on windows 10.  Systems configurations for all 3 systems are completely different.

**Comment by DanielGibson** [comment]
A proper backtrace from the debugger would be really helpful to see who calls idRenderWorldLocal::BoundsInAreas() with invalid bounds - same for the other crash.

**Comment by revility** [comment]
I've had no luck getting the debugger going :/
The crashes are rare.  I've gone for over a week and not seen them during constant test and plays.  This makes it hard for me to replicate.  Hopefully fixing all the console warnings in the old mod helps out with this.
